config/routes.rb
Rails.application.routes.draw do
      resources :equipment
      resources :user, only: [:new, :create, :show]
      resources :workout_type, only: [:index, :create, :show]
      resources :muscle_group, only: [:index, :show, :create]
      resources :workout
 
  get "/home", to: "equipment#index"
	root to: 'equipment#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/login", to: "sessions#login"
  post "/sessions", to: "sessions#sessions"
  delete "/logout", to: "sessions#logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	has_many :equipment_workouts
	has_many :workouts, through: :equipment_workouts

end

app/models/equipment_workout.rb
class EquipmentWorkout < ApplicationRecord
	belongs_to :equipment
	belongs_to :workout

end

app/models/muscle_group.rb
class MuscleGroup < ApplicationRecord
	belongs_to :workout_type
	has_many :muscle_group_workouts
	has_many :workouts, through: :muscle_group_workouts
end

app/models/muscle_group_workout.rb
class MuscleGroupWorkout < ApplicationRecord
	belongs_to :muscle_group
	belongs_to :workout
end

app/models/user.rb
class User < ApplicationRecord
	def password=(password)
    self.password_hash = BCrypt::Password.create(password)
  end

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end


end

app/models/workout.rb
class Workout < ApplicationRecord
	has_many :equipment_workouts
    has_many :equipments, through: :equipment_workouts

    has_many :muscle_group_workouts
    has_many :muscle_groups, through: :muscle_group_workouts
end

app/models/workout_type.rb
class WorkoutType < ApplicationRecord
	has_many :muscle_groups

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :null_session
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  def index
    @equipments = Equipment.all
  end
  def create
    equipment_ids = params[:eq_id]
    redirect_to controller: 'muscle_group', action: 'index', eq_ids: equipment_ids
  end

  def show  
    id = params[:id].to_i
    @equipment = Equipment.find(id)
  end



end

app/controllers/muscle_group_controller.rb
class MuscleGroupController < ApplicationController
    respond_to :js, :json, :html

  def index

    

    # p "*"*100
    # equipment = params.keys[0].split
    # arr = equipment[0].split(',')
    # p @equipment_ids = arr.each_index.select{|i| arr[i] == "true"}
    @muscle_groups = MuscleGroup.all
    @workout_types = WorkoutType.all

    # p @equipment_ids = params[:eq_ids]
    # p "hello"*100
  end

  def show

    @muscle_group = MuscleGroup.find_by(id: params[:id])
  end

  def create
    equipment = params.keys[0].split
    arr = equipment[0].split(',')
    p @equipment_ids = arr.each_index.select{|i| arr[i] == "true"}

  	p '*'*50
  	p params
  	p '*'*50
  	# redirect_to controller: 'workout', action: 'index', equipment_ids: params[:muscle_group][:equipment_ids].split(" "), muscle_ids: params[:ms_id]
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper
	def login
	end

	def sessions
		@user = User.find_by(email: params[:sessions][:email])
		if @user.password == params[:sessions][:password]
			login_user(@user)
			redirect_to "/"
		else
			redirect_to "/login"
		end
	end

	def logout
		logout_user
		redirect_to "/"
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	include SessionsHelper
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.password = user_params[:password_hash]
		if @user.save
			login_user(@user)
			redirect_to '/'
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:email, :password_hash)
	end
end

app/controllers/workout_controller.rb
class WorkoutController < ApplicationController
  def index
  	# change to workouts where id's of equipment and muscle groups match
    


    @workouts = Workout.all
    # equipment_ids = params[:equipment_ids]
    # muscle_ids = params[:muscle_ids]
    # equipment_ids = equipment_ids.map(&:to_i)
    # @equipment_list = Equipment.find(equipment_ids)
    # muscle_ids = muscle_ids.map(&:to_i)
    # @muscle_group_list =  MuscleGroup.find(muscle_ids)

    # view_arr = []
    # eq_list_arr = []
    # @equipment_list.each do |eq|
    #   eq.workouts.each do |eqwk|
    #     eq_list_arr << eqwk.name
    #   end
    # end

    # @muscle_group_list.each do |mg|
    #   mg.workouts.each do |mgwk|
    #     view_arr << mgwk.name if eq_list_arr.include?(mgwk.name)
    #   end
    # end
    # @view_list = view_arr

  end
  def create
    p "v^"*100
    p params
  end




end

app/controllers/workout_type_controller.rb
class WorkoutTypeController < ApplicationController
	def index
		@workout_types = WorkoutType.all
    @equipment_ids = params[:eq_ids]
	end

  def create
    muscle_ids = params[:ms_id]
    redirect_to controller: 'muscle_group', action: 'index', muscle_ids: muscle_ids
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login_user(user)
		session[:user_id] = user.id
	end

	def logout_user
		session.clear
	end

	def current_user
		if session[:user_id]
			User.find(session[:user_id])
		else
			nil
		end
	end
end

app/views/equipment/index.html.erb
<%= react_component 'Equipments', { data: @equipments } %>

app/views/equipment/show.html.erb
<%= react_component 'Equipment', { data: @equipment } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adaptifit</title>



  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">



    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
    <%= yield %>
  </body>
</html>

app/views/muscle_group/index.html.erb
<%= react_component 'MuscleGroups', { data: @workout_types, data1: @muscle_groups } %>

app/views/muscle_group/show.html.erb
<h2> <%= @muscle_group.name %> </h2>

<ul>
<% @.workouts.each do |workout| %>
  <li><%= workout.name %></li>
  <%= workout.description %>
<% end %>
</ul>

<!-- show equipment.workouts and musclegroup.workouts the same between the two  -->

app/views/user/new.html.erb
<h2>Register</h2>

<%= form_for @user, url: user_index_path(@user), html: {method: :post} do |f| %>
	email: <%= f.text_field :email %><br>
	password: <%= f.password_field :password_hash %><br>
	<%= f.submit %>
<% end %>

app/views/workout/index.html.erb
ALL EQUIPMENT WORKOUTS


<% @view_list.each do |workout| %>
	<%= workout %>
	<br>
<%end%>



<%#= react_component 'Workouts', {data: @workouts} %>